import type { RegistryItem } from './schema';

export const components: RegistryItem[] = [
  {
    name: 'icon',
    type: 'component',
    displayName: 'Icon',
    description: 'Icon component with support for all design system icons',
    files: [
      {
        path: 'templates/components/Icon.tsx',
        target: 'components/Icon.tsx',
        type: 'component',
      },
      {
        path: 'templates/components/Icon.css',
        target: 'components/Icon.css',
        type: 'style',
      },
      // SVG icon assets (88 icons)
      { path: 'templates/assets/svg/icons/AIR_AC_twin_engine.svg', target: 'assets/svg/icons/AIR_AC_twin_engine.svg', type: 'component' },
      { path: 'templates/assets/svg/icons/AIR_APU.svg', target: 'assets/svg/icons/AIR_APU.svg', type: 'component' },
      { path: 'templates/assets/svg/icons/AIR_Airbus.svg', target: 'assets/svg/icons/AIR_Airbus.svg', type: 'component' },
      { path: 'templates/assets/svg/icons/AIR_Chatbot.svg', target: 'assets/svg/icons/AIR_Chatbot.svg', type: 'component' },
      { path: 'templates/assets/svg/icons/AIR_Facebook.svg', target: 'assets/svg/icons/AIR_Facebook.svg', type: 'component' },
      { path: 'templates/assets/svg/icons/AIR_GitHub.svg', target: 'assets/svg/icons/AIR_GitHub.svg', type: 'component' },
      { path: 'templates/assets/svg/icons/AIR_Google.svg', target: 'assets/svg/icons/AIR_Google.svg', type: 'component' },
      { path: 'templates/assets/svg/icons/AIR_Instagram.svg', target: 'assets/svg/icons/AIR_Instagram.svg', type: 'component' },
      { path: 'templates/assets/svg/icons/AIR_Linkedin.svg', target: 'assets/svg/icons/AIR_Linkedin.svg', type: 'component' },
      { path: 'templates/assets/svg/icons/AIR_SAP.svg', target: 'assets/svg/icons/AIR_SAP.svg', type: 'component' },
      { path: 'templates/assets/svg/icons/AIR_SVG.svg', target: 'assets/svg/icons/AIR_SVG.svg', type: 'component' },
      { path: 'templates/assets/svg/icons/AIR_Skywise.svg', target: 'assets/svg/icons/AIR_Skywise.svg', type: 'component' },
      { path: 'templates/assets/svg/icons/AIR_X.svg', target: 'assets/svg/icons/AIR_X.svg', type: 'component' },
      { path: 'templates/assets/svg/icons/AIR_XLS.svg', target: 'assets/svg/icons/AIR_XLS.svg', type: 'component' },
      { path: 'templates/assets/svg/icons/AIR_Youtube.svg', target: 'assets/svg/icons/AIR_Youtube.svg', type: 'component' },
      { path: 'templates/assets/svg/icons/AIR_airport.svg', target: 'assets/svg/icons/AIR_airport.svg', type: 'component' },
      { path: 'templates/assets/svg/icons/AIR_arrival.svg', target: 'assets/svg/icons/AIR_arrival.svg', type: 'component' },
      { path: 'templates/assets/svg/icons/AIR_departure.svg', target: 'assets/svg/icons/AIR_departure.svg', type: 'component' },
      { path: 'templates/assets/svg/icons/AIR_engine.svg', target: 'assets/svg/icons/AIR_engine.svg', type: 'component' },
      { path: 'templates/assets/svg/icons/AIR_fleet.svg', target: 'assets/svg/icons/AIR_fleet.svg', type: 'component' },
      { path: 'templates/assets/svg/icons/AIR_ground_In.svg', target: 'assets/svg/icons/AIR_ground_In.svg', type: 'component' },
      { path: 'templates/assets/svg/icons/AIR_ground_out.svg', target: 'assets/svg/icons/AIR_ground_out.svg', type: 'component' },
      { path: 'templates/assets/svg/icons/AIR_landing_gear.svg', target: 'assets/svg/icons/AIR_landing_gear.svg', type: 'component' },
      { path: 'templates/assets/svg/icons/AIR_life_vest.svg', target: 'assets/svg/icons/AIR_life_vest.svg', type: 'component' },
      { path: 'templates/assets/svg/icons/AIR_side.svg', target: 'assets/svg/icons/AIR_side.svg', type: 'component' },
      { path: 'templates/assets/svg/icons/AIR_spinner.svg', target: 'assets/svg/icons/AIR_spinner.svg', type: 'component' },
      { path: 'templates/assets/svg/icons/AIR_tail.svg', target: 'assets/svg/icons/AIR_tail.svg', type: 'component' },
      { path: 'templates/assets/svg/icons/Airbus_logo.svg', target: 'assets/svg/icons/Airbus_logo.svg', type: 'component' },
      { path: 'templates/assets/svg/icons/account_balance.svg', target: 'assets/svg/icons/account_balance.svg', type: 'component' },
      { path: 'templates/assets/svg/icons/account_circle.svg', target: 'assets/svg/icons/account_circle.svg', type: 'component' },
      { path: 'templates/assets/svg/icons/add.svg', target: 'assets/svg/icons/add.svg', type: 'component' },
      { path: 'templates/assets/svg/icons/airline_seat_recline_extra.svg', target: 'assets/svg/icons/airline_seat_recline_extra.svg', type: 'component' },
      { path: 'templates/assets/svg/icons/apps.svg', target: 'assets/svg/icons/apps.svg', type: 'component' },
      { path: 'templates/assets/svg/icons/arrow_back.svg', target: 'assets/svg/icons/arrow_back.svg', type: 'component' },
      { path: 'templates/assets/svg/icons/arrow_downward.svg', target: 'assets/svg/icons/arrow_downward.svg', type: 'component' },
      { path: 'templates/assets/svg/icons/autorenew.svg', target: 'assets/svg/icons/autorenew.svg', type: 'component' },
      { path: 'templates/assets/svg/icons/balance.svg', target: 'assets/svg/icons/balance.svg', type: 'component' },
      { path: 'templates/assets/svg/icons/broken_image.svg', target: 'assets/svg/icons/broken_image.svg', type: 'component' },
      { path: 'templates/assets/svg/icons/calendar_month.svg', target: 'assets/svg/icons/calendar_month.svg', type: 'component' },
      { path: 'templates/assets/svg/icons/cancel.svg', target: 'assets/svg/icons/cancel.svg', type: 'component' },
      { path: 'templates/assets/svg/icons/check.svg', target: 'assets/svg/icons/check.svg', type: 'component' },
      { path: 'templates/assets/svg/icons/check_box.svg', target: 'assets/svg/icons/check_box.svg', type: 'component' },
      { path: 'templates/assets/svg/icons/check_box_outline_blank.svg', target: 'assets/svg/icons/check_box_outline_blank.svg', type: 'component' },
      { path: 'templates/assets/svg/icons/close.svg', target: 'assets/svg/icons/close.svg', type: 'component' },
      { path: 'templates/assets/svg/icons/code.svg', target: 'assets/svg/icons/code.svg', type: 'component' },
      { path: 'templates/assets/svg/icons/construction.svg', target: 'assets/svg/icons/construction.svg', type: 'component' },
      { path: 'templates/assets/svg/icons/content_copy.svg', target: 'assets/svg/icons/content_copy.svg', type: 'component' },
      { path: 'templates/assets/svg/icons/dark_mode.svg', target: 'assets/svg/icons/dark_mode.svg', type: 'component' },
      { path: 'templates/assets/svg/icons/delete.svg', target: 'assets/svg/icons/delete.svg', type: 'component' },
      { path: 'templates/assets/svg/icons/description.svg', target: 'assets/svg/icons/description.svg', type: 'component' },
      { path: 'templates/assets/svg/icons/download.svg', target: 'assets/svg/icons/download.svg', type: 'component' },
      { path: 'templates/assets/svg/icons/dropdown.svg', target: 'assets/svg/icons/dropdown.svg', type: 'component' },
      { path: 'templates/assets/svg/icons/edit.svg', target: 'assets/svg/icons/edit.svg', type: 'component' },
      { path: 'templates/assets/svg/icons/emoji_emotions.svg', target: 'assets/svg/icons/emoji_emotions.svg', type: 'component' },
      { path: 'templates/assets/svg/icons/error.svg', target: 'assets/svg/icons/error.svg', type: 'component' },
      { path: 'templates/assets/svg/icons/event.svg', target: 'assets/svg/icons/event.svg', type: 'component' },
      { path: 'templates/assets/svg/icons/filter.svg', target: 'assets/svg/icons/filter.svg', type: 'component' },
      { path: 'templates/assets/svg/icons/filter_row.svg', target: 'assets/svg/icons/filter_row.svg', type: 'component' },
      { path: 'templates/assets/svg/icons/folder.svg', target: 'assets/svg/icons/folder.svg', type: 'component' },
      { path: 'templates/assets/svg/icons/folder_open.svg', target: 'assets/svg/icons/folder_open.svg', type: 'component' },
      { path: 'templates/assets/svg/icons/forum.svg', target: 'assets/svg/icons/forum.svg', type: 'component' },
      { path: 'templates/assets/svg/icons/groups.svg', target: 'assets/svg/icons/groups.svg', type: 'component' },
      { path: 'templates/assets/svg/icons/info.svg', target: 'assets/svg/icons/info.svg', type: 'component' },
      { path: 'templates/assets/svg/icons/keyboard_arrow_down.svg', target: 'assets/svg/icons/keyboard_arrow_down.svg', type: 'component' },
      { path: 'templates/assets/svg/icons/keyboard_arrow_right.svg', target: 'assets/svg/icons/keyboard_arrow_right.svg', type: 'component' },
      { path: 'templates/assets/svg/icons/keyboard_arrow_up.svg', target: 'assets/svg/icons/keyboard_arrow_up.svg', type: 'component' },
      { path: 'templates/assets/svg/icons/light_mode.svg', target: 'assets/svg/icons/light_mode.svg', type: 'component' },
      { path: 'templates/assets/svg/icons/list.svg', target: 'assets/svg/icons/list.svg', type: 'component' },
      { path: 'templates/assets/svg/icons/menu.svg', target: 'assets/svg/icons/menu.svg', type: 'component' },
      { path: 'templates/assets/svg/icons/monetization_on.svg', target: 'assets/svg/icons/monetization_on.svg', type: 'component' },
      { path: 'templates/assets/svg/icons/more_horiz.svg', target: 'assets/svg/icons/more_horiz.svg', type: 'component' },
      { path: 'templates/assets/svg/icons/navigate_before.svg', target: 'assets/svg/icons/navigate_before.svg', type: 'component' },
      { path: 'templates/assets/svg/icons/navigate_next.svg', target: 'assets/svg/icons/navigate_next.svg', type: 'component' },
      { path: 'templates/assets/svg/icons/notifications.svg', target: 'assets/svg/icons/notifications.svg', type: 'component' },
      { path: 'templates/assets/svg/icons/open_in_new.svg', target: 'assets/svg/icons/open_in_new.svg', type: 'component' },
      { path: 'templates/assets/svg/icons/play.svg', target: 'assets/svg/icons/play.svg', type: 'component' },
      { path: 'templates/assets/svg/icons/remove.svg', target: 'assets/svg/icons/remove.svg', type: 'component' },
      { path: 'templates/assets/svg/icons/search.svg', target: 'assets/svg/icons/search.svg', type: 'component' },
      { path: 'templates/assets/svg/icons/settings.svg', target: 'assets/svg/icons/settings.svg', type: 'component' },
      { path: 'templates/assets/svg/icons/share.svg', target: 'assets/svg/icons/share.svg', type: 'component' },
      { path: 'templates/assets/svg/icons/speed.svg', target: 'assets/svg/icons/speed.svg', type: 'component' },
      { path: 'templates/assets/svg/icons/star.svg', target: 'assets/svg/icons/star.svg', type: 'component' },
      { path: 'templates/assets/svg/icons/star_border.svg', target: 'assets/svg/icons/star_border.svg', type: 'component' },
      { path: 'templates/assets/svg/icons/trending_down.svg', target: 'assets/svg/icons/trending_down.svg', type: 'component' },
      { path: 'templates/assets/svg/icons/trending_up.svg', target: 'assets/svg/icons/trending_up.svg', type: 'component' },
      { path: 'templates/assets/svg/icons/upload.svg', target: 'assets/svg/icons/upload.svg', type: 'component' },
      { path: 'templates/assets/svg/icons/visibility.svg', target: 'assets/svg/icons/visibility.svg', type: 'component' },
      { path: 'templates/assets/svg/icons/warning.svg', target: 'assets/svg/icons/warning.svg', type: 'component' },
    ],
    cssImports: [],
  },
  {
    name: 'button',
    type: 'component',
    displayName: 'Button',
    description: 'Button component with variants, sizes, and icon support',
    files: [
      {
        path: 'templates/components/Button.tsx',
        target: 'components/Button.tsx',
        type: 'component',
      },
      {
        path: 'templates/components/Button.css',
        target: 'components/Button.css',
        type: 'style',
      },
    ],
    dependencies: ['icon'],
    cssImports: [
      '@/design-system/tokens/typography.css',
      '@/design-system/tokens/colors.css',
      '@/design-system/tokens/radius.css',
    ],
  },
  {
    name: 'icon-button',
    type: 'component',
    displayName: 'IconButton',
    description: 'Icon-only button with variants and sizes',
    files: [
      {
        path: 'templates/components/IconButton.tsx',
        target: 'components/IconButton.tsx',
        type: 'component',
      },
      {
        path: 'templates/components/IconButton.css',
        target: 'components/IconButton.css',
        type: 'style',
      },
    ],
    dependencies: ['icon', 'tooltip'],
    cssImports: [
      '@/design-system/tokens/colors.css',
      '@/design-system/tokens/radius.css',
    ],
  },
  {
    name: 'tab',
    type: 'component',
    displayName: 'Tab',
    description: 'Tab component with icon support and variants',
    files: [
      {
        path: 'templates/components/Tab.tsx',
        target: 'components/Tab.tsx',
        type: 'component',
      },
      {
        path: 'templates/components/Tab.css',
        target: 'components/Tab.css',
        type: 'style',
      },
    ],
    dependencies: ['icon'],
    cssImports: [
      '@/design-system/tokens/typography.css',
      '@/design-system/tokens/colors.css',
    ],
  },
  {
    name: 'tool-icons',
    type: 'component',
    displayName: 'ToolIcons',
    description: 'Tool icons component with Light and Dark mode support',
    files: [
      {
        path: 'templates/components/ToolIcons.tsx',
        target: 'components/ToolIcons.tsx',
        type: 'component',
      },
      {
        path: 'templates/components/ToolIcons.css',
        target: 'components/ToolIcons.css',
        type: 'style',
      },
      // PNG tool icon assets
      {
        path: 'templates/assets/png/tool-icons/ac-config-dark.png',
        target: 'assets/png/tool-icons/ac-config-dark.png',
        type: 'component',
      },
      {
        path: 'templates/assets/png/tool-icons/ac-config-light.png',
        target: 'assets/png/tool-icons/ac-config-light.png',
        type: 'component',
      },
      {
        path: 'templates/assets/png/tool-icons/airline-business-planner-dark.png',
        target: 'assets/png/tool-icons/airline-business-planner-dark.png',
        type: 'component',
      },
      {
        path: 'templates/assets/png/tool-icons/airline-business-planner-light.png',
        target: 'assets/png/tool-icons/airline-business-planner-light.png',
        type: 'component',
      },
      {
        path: 'templates/assets/png/tool-icons/airline-simulator-dark.png',
        target: 'assets/png/tool-icons/airline-simulator-dark.png',
        type: 'component',
      },
      {
        path: 'templates/assets/png/tool-icons/airline-simulator-light.png',
        target: 'assets/png/tool-icons/airline-simulator-light.png',
        type: 'component',
      },
      {
        path: 'templates/assets/png/tool-icons/airscout-dark.png',
        target: 'assets/png/tool-icons/airscout-dark.png',
        type: 'component',
      },
      {
        path: 'templates/assets/png/tool-icons/airscout-light.png',
        target: 'assets/png/tool-icons/airscout-light.png',
        type: 'component',
      },
      {
        path: 'templates/assets/png/tool-icons/aoa-dark.png',
        target: 'assets/png/tool-icons/aoa-dark.png',
        type: 'component',
      },
      {
        path: 'templates/assets/png/tool-icons/aoa-light.png',
        target: 'assets/png/tool-icons/aoa-light.png',
        type: 'component',
      },
      {
        path: 'templates/assets/png/tool-icons/atmosphere-dark.png',
        target: 'assets/png/tool-icons/atmosphere-dark.png',
        type: 'component',
      },
      {
        path: 'templates/assets/png/tool-icons/atmosphere-light.png',
        target: 'assets/png/tool-icons/atmosphere-light.png',
        type: 'component',
      },
      {
        path: 'templates/assets/png/tool-icons/cabin-crew-dark.png',
        target: 'assets/png/tool-icons/cabin-crew-dark.png',
        type: 'component',
      },
      {
        path: 'templates/assets/png/tool-icons/cabin-crew-light.png',
        target: 'assets/png/tool-icons/cabin-crew-light.png',
        type: 'component',
      },
      {
        path: 'templates/assets/png/tool-icons/economics-dark.png',
        target: 'assets/png/tool-icons/economics-dark.png',
        type: 'component',
      },
      {
        path: 'templates/assets/png/tool-icons/economics-light.png',
        target: 'assets/png/tool-icons/economics-light.png',
        type: 'component',
      },
      {
        path: 'templates/assets/png/tool-icons/economicslite-dark.png',
        target: 'assets/png/tool-icons/economicslite-dark.png',
        type: 'component',
      },
      {
        path: 'templates/assets/png/tool-icons/economicslite-light.png',
        target: 'assets/png/tool-icons/economicslite-light.png',
        type: 'component',
      },
      {
        path: 'templates/assets/png/tool-icons/fellofly-dark.png',
        target: 'assets/png/tool-icons/fellofly-dark.png',
        type: 'component',
      },
      {
        path: 'templates/assets/png/tool-icons/fellofly-light.png',
        target: 'assets/png/tool-icons/fellofly-light.png',
        type: 'component',
      },
      {
        path: 'templates/assets/png/tool-icons/lopaexplorer-dark.png',
        target: 'assets/png/tool-icons/lopaexplorer-dark.png',
        type: 'component',
      },
      {
        path: 'templates/assets/png/tool-icons/lopaexplorer-light.png',
        target: 'assets/png/tool-icons/lopaexplorer-light.png',
        type: 'component',
      },
      {
        path: 'templates/assets/png/tool-icons/maintenance-dark.png',
        target: 'assets/png/tool-icons/maintenance-dark.png',
        type: 'component',
      },
      {
        path: 'templates/assets/png/tool-icons/maintenance-light.png',
        target: 'assets/png/tool-icons/maintenance-light.png',
        type: 'component',
      },
      {
        path: 'templates/assets/png/tool-icons/missionlite-dark.png',
        target: 'assets/png/tool-icons/missionlite-dark.png',
        type: 'component',
      },
      {
        path: 'templates/assets/png/tool-icons/missionlite-light.png',
        target: 'assets/png/tool-icons/missionlite-light.png',
        type: 'component',
      },
      {
        path: 'templates/assets/png/tool-icons/navdb-editor-dark.png',
        target: 'assets/png/tool-icons/navdb-editor-dark.png',
        type: 'component',
      },
      {
        path: 'templates/assets/png/tool-icons/navdb-editor-light.png',
        target: 'assets/png/tool-icons/navdb-editor-light.png',
        type: 'component',
      },
      {
        path: 'templates/assets/png/tool-icons/network-dark.png',
        target: 'assets/png/tool-icons/network-dark.png',
        type: 'component',
      },
      {
        path: 'templates/assets/png/tool-icons/network-fam-dark.png',
        target: 'assets/png/tool-icons/network-fam-dark.png',
        type: 'component',
      },
      {
        path: 'templates/assets/png/tool-icons/network-fam-light.png',
        target: 'assets/png/tool-icons/network-fam-light.png',
        type: 'component',
      },
      {
        path: 'templates/assets/png/tool-icons/network-light.png',
        target: 'assets/png/tool-icons/network-light.png',
        type: 'component',
      },
      {
        path: 'templates/assets/png/tool-icons/network-rotation-dark.png',
        target: 'assets/png/tool-icons/network-rotation-dark.png',
        type: 'component',
      },
      {
        path: 'templates/assets/png/tool-icons/network-rotation-light.png',
        target: 'assets/png/tool-icons/network-rotation-light.png',
        type: 'component',
      },
      {
        path: 'templates/assets/png/tool-icons/network-tam-dark.png',
        target: 'assets/png/tool-icons/network-tam-dark.png',
        type: 'component',
      },
      {
        path: 'templates/assets/png/tool-icons/network-tam-light.png',
        target: 'assets/png/tool-icons/network-tam-light.png',
        type: 'component',
      },
      {
        path: 'templates/assets/png/tool-icons/skyfinesse-dark.png',
        target: 'assets/png/tool-icons/skyfinesse-dark.png',
        type: 'component',
      },
      {
        path: 'templates/assets/png/tool-icons/skyfinesse-light.png',
        target: 'assets/png/tool-icons/skyfinesse-light.png',
        type: 'component',
      },
      {
        path: 'templates/assets/png/tool-icons/trajopt-dark.png',
        target: 'assets/png/tool-icons/trajopt-dark.png',
        type: 'component',
      },
      {
        path: 'templates/assets/png/tool-icons/trajopt-light.png',
        target: 'assets/png/tool-icons/trajopt-light.png',
        type: 'component',
      },
      {
        path: 'templates/assets/png/tool-icons/weight-builder-dark.png',
        target: 'assets/png/tool-icons/weight-builder-dark.png',
        type: 'component',
      },
      {
        path: 'templates/assets/png/tool-icons/weight-builder-light.png',
        target: 'assets/png/tool-icons/weight-builder-light.png',
        type: 'component',
      },
    ],
    dependencies: [],
    cssImports: [],
  },
  {
    name: 'select',
    type: 'component',
    displayName: 'Select',
    description: 'Accessible select component based on Radix UI with sizes and states',
    files: [
      {
        path: 'templates/components/Select.tsx',
        target: 'components/Select.tsx',
        type: 'component',
      },
      {
        path: 'templates/components/Select.css',
        target: 'components/Select.css',
        type: 'style',
      },
    ],
    dependencies: ['icon'],
    externalDependencies: {
      '@radix-ui/react-select': '^2.1.2',
    },
    cssImports: [
      '@/design-system/tokens/typography.css',
      '@/design-system/tokens/colors.css',
      '@/design-system/tokens/radius.css',
    ],
  },
  {
    name: 'vselect',
    type: 'component',
    displayName: 'VSelect',
    description: 'Vanilla select component (pure React) with sizes and states',
    files: [
      {
        path: 'templates/components/VSelect.tsx',
        target: 'components/VSelect.tsx',
        type: 'component',
      },
      {
        path: 'templates/components/VSelect.css',
        target: 'components/VSelect.css',
        type: 'style',
      },
    ],
    dependencies: ['icon'],
    cssImports: [
      '@/design-system/tokens/typography.css',
      '@/design-system/tokens/colors.css',
      '@/design-system/tokens/radius.css',
    ],
  },
  {
    name: 'button-group',
    type: 'component',
    displayName: 'ButtonGroup',
    description: 'Toggle button group for single selection',
    files: [
      {
        path: 'templates/components/ButtonGroup.tsx',
        target: 'components/ButtonGroup.tsx',
        type: 'component',
      },
      {
        path: 'templates/components/ButtonGroup.css',
        target: 'components/ButtonGroup.css',
        type: 'style',
      },
    ],
    dependencies: [],
    cssImports: [
      '@/design-system/tokens/typography.css',
      '@/design-system/tokens/colors.css',
      '@/design-system/tokens/radius.css',
    ],
  },
  {
    name: 'checkbox',
    type: 'component',
    displayName: 'Checkbox',
    description: 'Accessible checkbox component based on Radix UI with sizes and states',
    files: [
      {
        path: 'templates/components/Checkbox.tsx',
        target: 'components/Checkbox.tsx',
        type: 'component',
      },
      {
        path: 'templates/components/Checkbox.css',
        target: 'components/Checkbox.css',
        type: 'style',
      },
    ],
    dependencies: ['icon'],
    externalDependencies: {
      '@radix-ui/react-checkbox': '^1.3.3',
    },
    cssImports: [
      '@/design-system/tokens/typography.css',
      '@/design-system/tokens/colors.css',
      '@/design-system/tokens/radius.css',
    ],
  },
  {
    name: 'vcheckbox',
    type: 'component',
    displayName: 'VCheckbox',
    description: 'Vanilla checkbox component (pure React) with sizes and states',
    files: [
      {
        path: 'templates/components/VCheckbox.tsx',
        target: 'components/VCheckbox.tsx',
        type: 'component',
      },
      {
        path: 'templates/components/VCheckbox.css',
        target: 'components/VCheckbox.css',
        type: 'style',
      },
    ],
    dependencies: ['icon'],
    cssImports: [
      '@/design-system/tokens/typography.css',
      '@/design-system/tokens/colors.css',
      '@/design-system/tokens/radius.css',
    ],
  },
  {
    name: 'toggle',
    type: 'component',
    displayName: 'Toggle',
    description: 'Accessible toggle switch component based on Radix UI Switch',
    files: [
      {
        path: 'templates/components/Toggle.tsx',
        target: 'components/Toggle.tsx',
        type: 'component',
      },
      {
        path: 'templates/components/Toggle.css',
        target: 'components/Toggle.css',
        type: 'style',
      },
    ],
    dependencies: [],
    externalDependencies: {
      '@radix-ui/react-switch': '^1.2.6',
    },
    cssImports: [
      '@/design-system/tokens/typography.css',
      '@/design-system/tokens/colors.css',
    ],
  },
  {
    name: 'vtoggle',
    type: 'component',
    displayName: 'VToggle',
    description: 'Vanilla toggle switch component (pure React) for boolean selections',
    files: [
      {
        path: 'templates/components/VToggle.tsx',
        target: 'components/VToggle.tsx',
        type: 'component',
      },
      {
        path: 'templates/components/VToggle.css',
        target: 'components/VToggle.css',
        type: 'style',
      },
    ],
    dependencies: [],
    cssImports: [
      '@/design-system/tokens/typography.css',
      '@/design-system/tokens/colors.css',
    ],
  },
  {
    name: 'text-input',
    type: 'component',
    displayName: 'TextInput',
    description: 'Text input component with sizes, states, icons and validation',
    files: [
      {
        path: 'templates/components/TextInput.tsx',
        target: 'components/TextInput.tsx',
        type: 'component',
      },
      {
        path: 'templates/components/TextInput.css',
        target: 'components/TextInput.css',
        type: 'style',
      },
    ],
    dependencies: ['icon'],
    cssImports: [
      '@/design-system/tokens/typography.css',
      '@/design-system/tokens/colors.css',
      '@/design-system/tokens/radius.css',
    ],
  },
  {
    name: 'number-input',
    type: 'component',
    displayName: 'NumberInput',
    description: 'Numeric stepper input with increment/decrement buttons',
    files: [
      {
        path: 'templates/components/NumberInput.tsx',
        target: 'components/NumberInput.tsx',
        type: 'component',
      },
      {
        path: 'templates/components/NumberInput.css',
        target: 'components/NumberInput.css',
        type: 'style',
      },
    ],
    dependencies: ['icon', 'icon-button'],
    cssImports: [
      '@/design-system/tokens/typography.css',
      '@/design-system/tokens/colors.css',
      '@/design-system/tokens/radius.css',
    ],
  },
  {
    name: 'tooltip',
    type: 'component',
    displayName: 'Tooltip',
    description: 'Radix UI-based tooltip with compound component pattern',
    files: [
      {
        path: 'templates/components/Tooltip.tsx',
        target: 'components/Tooltip.tsx',
        type: 'component',
      },
      {
        path: 'templates/components/Tooltip.css',
        target: 'components/Tooltip.css',
        type: 'style',
      },
    ],
    dependencies: [],
    externalDependencies: {
      '@radix-ui/react-tooltip': '^1.2.8',
    },
    cssImports: [
      '@/design-system/tokens/typography.css',
      '@/design-system/tokens/colors.css',
      '@/design-system/tokens/radius.css',
    ],
  },
  {
    name: 'panel-study-name',
    type: 'component',
    displayName: 'PanelStudyName',
    description: 'Clickable study name label with edit icon for dark corporate panels',
    files: [
      {
        path: 'templates/components/PanelStudyName.tsx',
        target: 'components/PanelStudyName.tsx',
        type: 'component',
      },
      {
        path: 'templates/components/PanelStudyName.css',
        target: 'components/PanelStudyName.css',
        type: 'style',
      },
    ],
    dependencies: ['icon'],
    cssImports: [
      '@/design-system/tokens/colors.css',
      '@/design-system/tokens/radius.css',
    ],
  },
  {
    name: 'panel-button',
    type: 'component',
    displayName: 'PanelButton',
    description: 'Navigation button for dark side panels with expanded/collapsed modes',
    files: [
      {
        path: 'templates/components/PanelButton.tsx',
        target: 'components/PanelButton.tsx',
        type: 'component',
      },
      {
        path: 'templates/components/PanelButton.css',
        target: 'components/PanelButton.css',
        type: 'style',
      },
    ],
    dependencies: ['icon', 'tooltip'],
    cssImports: [
      '@/design-system/tokens/typography.css',
      '@/design-system/tokens/colors.css',
      '@/design-system/tokens/radius.css',
    ],
  },
  {
    name: 'spinner',
    type: 'component',
    displayName: 'Spinner',
    description: 'Rotating loading indicator',
    files: [
      {
        path: 'templates/components/Spinner.tsx',
        target: 'components/Spinner.tsx',
        type: 'component',
      },
      {
        path: 'templates/components/Spinner.css',
        target: 'components/Spinner.css',
        type: 'style',
      },
    ],
    dependencies: ['icon'],
    cssImports: [],
  },
  {
    name: 'panel-section-title',
    type: 'component',
    displayName: 'PanelSectionTitle',
    description: 'Section title label for dark corporate panels',
    files: [
      {
        path: 'templates/components/PanelSectionTitle.tsx',
        target: 'components/PanelSectionTitle.tsx',
        type: 'component',
      },
      {
        path: 'templates/components/PanelSectionTitle.css',
        target: 'components/PanelSectionTitle.css',
        type: 'style',
      },
    ],
    dependencies: [],
    cssImports: [],
  },
  {
    name: 'panel-group',
    type: 'component',
    displayName: 'PanelGroup',
    description: 'Collapsible group header for dark corporate panels with optional actions',
    files: [
      {
        path: 'templates/components/PanelGroup.tsx',
        target: 'components/PanelGroup.tsx',
        type: 'component',
      },
      {
        path: 'templates/components/PanelGroup.css',
        target: 'components/PanelGroup.css',
        type: 'style',
      },
    ],
    dependencies: ['icon'],
    cssImports: [],
  },
  {
    name: 'avatar',
    type: 'component',
    displayName: 'Avatar',
    description: 'Circular user initials indicator with auto-colored background and stack layout',
    files: [
      {
        path: 'templates/components/Avatar.tsx',
        target: 'components/Avatar.tsx',
        type: 'component',
      },
      {
        path: 'templates/components/Avatar.css',
        target: 'components/Avatar.css',
        type: 'style',
      },
    ],
    dependencies: ['tooltip'],
    cssImports: [
      '@/design-system/tokens/typography.css',
      '@/design-system/tokens/colors.css',
    ],
  },
  {
    name: 'chip',
    type: 'component',
    displayName: 'Chip',
    description: 'Pill-shaped badge for selections, filters, or tags with Selectable, ReadOnly, and Removable types',
    files: [
      {
        path: 'templates/components/Chip.tsx',
        target: 'components/Chip.tsx',
        type: 'component',
      },
      {
        path: 'templates/components/Chip.css',
        target: 'components/Chip.css',
        type: 'style',
      },
    ],
    dependencies: ['icon'],
    cssImports: [
      '@/design-system/tokens/typography.css',
      '@/design-system/tokens/colors.css',
    ],
  },
  {
    name: 'study-status',
    type: 'component',
    displayName: 'StudyStatus',
    description: 'Displays computation status of a study (Computed, Computing, Failed, Draft, Warning)',
    files: [
      {
        path: 'templates/components/StudyStatus.tsx',
        target: 'components/StudyStatus.tsx',
        type: 'component',
      },
      {
        path: 'templates/components/StudyStatus.css',
        target: 'components/StudyStatus.css',
        type: 'style',
      },
    ],
    dependencies: ['icon', 'spinner'],
    cssImports: [
      '@/design-system/tokens/typography.css',
      '@/design-system/tokens/colors.css',
    ],
  },
  {
    name: 'study-row',
    type: 'component',
    displayName: 'StudyRow',
    description: 'Table row displaying study information with status, configurable columns, and optional checkbox',
    files: [
      {
        path: 'templates/components/StudyRow.tsx',
        target: 'components/StudyRow.tsx',
        type: 'component',
      },
      {
        path: 'templates/components/StudyRow.css',
        target: 'components/StudyRow.css',
        type: 'style',
      },
    ],
    dependencies: ['checkbox', 'study-status', 'icon-button'],
    cssImports: [
      '@/design-system/tokens/typography.css',
      '@/design-system/tokens/colors.css',
    ],
  },
  {
    name: 'study-table-header',
    type: 'component',
    displayName: 'StudyTableHeader',
    description: 'Table header row for study lists with configurable columns and optional select-all checkbox',
    files: [
      {
        path: 'templates/components/StudyTableHeader.tsx',
        target: 'components/StudyTableHeader.tsx',
        type: 'component',
      },
      {
        path: 'templates/components/StudyTableHeader.css',
        target: 'components/StudyTableHeader.css',
        type: 'style',
      },
    ],
    dependencies: ['checkbox'],
    cssImports: [
      '@/design-system/tokens/typography.css',
      '@/design-system/tokens/colors.css',
    ],
  },
  {
    name: 'dropdown-menu',
    type: 'component',
    displayName: 'DropdownMenu',
    description: 'Accessible dropdown menu based on Radix UI with action items, checkbox items, sub-menus, and section labels',
    files: [
      {
        path: 'templates/components/DropdownMenu.tsx',
        target: 'components/DropdownMenu.tsx',
        type: 'component',
      },
      {
        path: 'templates/components/DropdownMenu.css',
        target: 'components/DropdownMenu.css',
        type: 'style',
      },
    ],
    dependencies: ['icon'],
    externalDependencies: {
      '@radix-ui/react-dropdown-menu': '^2.1.16',
    },
    cssImports: [
      '@/design-system/tokens/typography.css',
      '@/design-system/tokens/colors.css',
      '@/design-system/tokens/radius.css',
    ],
  },
];
